// Write version.js for a local run. Every page fetches ./version.js to notice
// a stale cached build; the deploy workflow generates it, so a plain clone had
// nothing to fetch and opened with a 404 in the console. `npm start` runs this
// first. version.js is gitignored, so it never rides into a commit.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const git = (cmd, fallback) => { try { return execSync(`git ${cmd}`, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch { return fallback; } };
const build = git('rev-list --count HEAD', '0');
const sha = git('rev-parse --short HEAD', 'local');
const iso = git('log -1 --format=%cI', new Date().toISOString());
const date = iso.slice(0, 10);

writeFileSync(new URL('../version.js', import.meta.url), `// Generated by scripts/version-local.mjs. Not committed.
(function () {
  window.__naasVersion = { build: ${build}, sha: "${sha}", date: "${date}", iso: "${iso}" };
})();
`);
console.log(`version.js: build ${build} (${sha}, ${date})`);
